#!/usr/bin/env sh

if ! command -v git-rightend >/dev/null; then
  oldDir="$(pwd)"
  cd /tmp
  git clone https://github.com/Right-End/GitRightEnd.git /tmp
  cd GitRightEnd
  . ./git-rightend-install
  cd -- "$oldDir"
fi

git-rightend pull
git-rightend add .
git-rightend commit
git-rightend push

